### PR TITLE
Adding async to zmq package

### PR DESCRIPTION
**Pull request by Clonkk**
* The async proc were already done by @jackhftang but added to the examples folder and thus not accessible (which is a shame beause it's very useful).
* Added std/ prefix before import.
* ~~Fix a missing a close in examples that could cause CI to hang indefinitely~~ apparently not fixed
* Added runnable exmaples instead of code block and added examples in the documentation
* Added CI to generate docs -> @Araq At your leisure, this requires  :  
  * creating ``gh-pages`` branch 
  * enabling github pages for the ``gh-pages`` branch on the ``docs`` folder. 
  * Adding link to the docs in relevant places such as website repo, readme etc.
  * The result can be seen in my fork https://clonkk.github.io/nim-zmq/zmq.html.

=> If you don't want to generate the docs, this can be removed from this PR.

* Bump to version v1.1.0

### CODE REVIEW

**Comment by Clonkk** [comment]
For some reason (I thought I fixed it, but apparently not) the CI sometimes fails and hang indefinitely.  I'll reopen this when I can do something. I'll reopen when it's fixed on my fork.

**Comment by Clonkk** [comment]
Apparently closing PR do not cancel associated jobs so https://github.com/nim-lang/nim-zmq/actions/runs/1067646494 will probably have to be cancelled manually.

Network testing on github CI is volatile; since running the examples wasn't really necessary so I ended making sure the examples compile but without running them.

**Comment by Clonkk** [comment]
Should the async proc be called ``sendAsync`` ``receiveAsync`` or ``æsyncSend``, ``asyncReceive`` to be consistent with other async package ?

**Comment by jackhftang** [comment]
@Clonkk I have no opinions on naming. There reasons why I put the procs in /test as an example and aside from zmq is that it makes `asyncdispatch` module as a required dependence. It seems to me that not everyone use (or like) std/asyncdispatch as their async task runner. And it is easy to copy-and-paste if users have read the examples.

**Comment by Araq** [comment]
I have no opinion on the names either.

**Pull request merged**
